In [7]:
print("; ".join(["gmail", "hotmail", "yahoo"]))
print("Hello ME".replace("ME", "Sanjana"))
print("This is my life.".startswith("This"))
print("This is my life.".endswith("life."))
print("This is a sentence.".upper())
print("AN ALL CAPS SENTENCE".lower())
print("gmail, hotmail, yahoo".split(", "))

gmail; hotmail; yahoo
Hello Sanjana
True
True
THIS IS A SENTENCE.
an all caps sentence
['gmail', 'hotmail', 'yahoo']


In [8]:
print(min(1, 2, 3, 4, 0, 2, 1))
print(max([1, 4, 9, 2, 5, 6, 8]))
print(abs(-99))
print(abs(42))
print(sum([1, 2, 3, 4, 5]))

0
9
99
42
15


In [9]:
nums = [55, 44, 33, 22, 11]

if all([i > 5 for i in nums]):
    print("All larger than 5")

if any([i % 2 == 0 for i in nums]):
    print("At least one is even")

for v in enumerate(nums):
    print(v)

All larger than 5
At least one is even
(0, 55)
(1, 44)
(2, 33)
(3, 22)
(4, 11)


In [13]:
import numpy as np 
a = "hello world"
print (a)

hello world


In [15]:
import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [24]:
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [21]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [20]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)
print(a.shape)

[1.+0.j 2.+0.j 3.+0.j]
(3,)


In [25]:
a = np.zeros((2,3))   # Create an array of all zeros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
b = np.ones((1,2))    # Create an array of all ones
print(b)

[[1. 1.]]


In [27]:
c = np.full((2,2), 8)  # Create a constant array
print(c) 

[[8 8]
 [8 8]]


In [28]:
d = np.eye(4)         # Create a 2x2 identity matrix
print(d) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e) 

[[0.92150414 0.20491877]
 [0.18675978 0.17414338]]


In [34]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[1:2, 1:3]  #row 1 and 2 and columns 1-3
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[6 7]]


In [35]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
print(bool_idx)     
print(a[bool_idx]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [36]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.add(x, y))    #same as print(x + y)
print(np.subtract(x, y))    #prints (x - y)
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [37]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [38]:
x = np.array([[1,2],[3,4]])
print(x.T)  #transpose of array

[[1 3]
 [2 4]]


In [39]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv, "\n") 

y = x + vv 
print(y) 
y[1,1]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


5

In [50]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
